### ISSUE TITLE
Building and more

### ISSUE THREAD

**Issue by yogitea** [bisdk/sdk#7]
I am running into issues when building this on MacOS Catalina.
What is the preferred setup to build this project?
Is there a required Java version?

My idea for the project would be to have a Docker container running the BiSecu<->SDK<->REST/MQTT communication or something to make deployment of this great tool much easier.
As the other people here stated it makes most sense to include this into home automation and docker seems to be working everywhere these days. 

Thank you for any hints or comments you might have!

**Comment by yogitea** [comment]
> Task :compileKotlinMacos FAILED
e: /*/sdk/src/commonMain/kotlin/org/bisdk/Encoding.kt: (3, 16): Unresolved reference: io
e: /*/sdk/src/commonMain/kotlin/org/bisdk/Encoding.kt: (61, 30): Unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
public fun Byte.toByteArray(): ByteArray defined in org.bisdk in file Encoding.kt
public fun Int.toByteArray(size: Int): ByteArray defined in org.bisdk in file Encoding.kt

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileKotlinMacos'.
> Compilation finished with errors

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':compileKotlinMacos'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$2.accept(ExecuteActionsTaskExecuter.java:121)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$2.accept(ExecuteActionsTaskExecuter.java:117)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:184)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ResolveIncrementalChangesTaskExecuter.execute(ResolveIncrementalChangesTaskExecuter.java:84)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionStateTaskExecuter.execute(ResolveBeforeExecutionStateTaskExecuter.java:74)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:109)
        at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionOutputsTaskExecuter.execute(ResolveBeforeExecutionOutputsTaskExecuter.java:67)
        at org.gradle.api.internal.tasks.execution.ResolveAfterPreviousExecutionStateTaskExecuter.execute(ResolveAfterPreviousExecutionStateTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:93)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:45)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:94)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:63)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:49)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:46)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:355)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:322)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:134)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:129)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:202)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:193)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:129)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.jetbrains.kotlin.backend.konan.KonanCompilationException: Compilation finished with errors
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion$mainNoExit$1.invoke(K2Native.kt:247)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion$mainNoExit$1.invoke(K2Native.kt:238)
        at org.jetbrains.kotlin.util.UtilKt.profileIf(Util.kt:27)
        at org.jetbrains.kotlin.util.UtilKt.profile(Util.kt:21)
        at org.jetbrains.kotlin.cli.bc.K2Native$Companion.mainNoExit(K2Native.kt:245)
        at org.jetbrains.kotlin.cli.bc.K2NativeKt.mainNoExit(K2Native.kt:376)
        at org.jetbrains.kotlin.cli.utilities.MainKt$daemonMain$1.invoke(main.kt:39)
        at org.jetbrains.kotlin.cli.utilities.MainKt$daemonMain$1.invoke(main.kt)
        at org.jetbrains.kotlin.cli.utilities.MainKt.mainImpl(main.kt:17)
        at org.jetbrains.kotlin.cli.utilities.MainKt.daemonMain(main.kt:39)
        at org.jetbrains.kotlin.compilerRunner.KonanCliRunner.run(KotlinNativeToolRunner.kt:206)
        at org.jetbrains.kotlin.gradle.tasks.AbstractKotlinNativeCompile.compile(KotlinNativeTasks.kt:278)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:103)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:48)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:41)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:28)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:705)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:672)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$4.run(ExecuteActionsTaskExecuter.java:338)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:327)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:312)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$200(ExecuteActionsTaskExecuter.java:75)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:158)
        at org.gradle.internal.execution.impl.steps.ExecuteStep.execute(ExecuteStep.java:46)
        at org.gradle.internal.execution.impl.steps.CancelExecutionStep.execute(CancelExecutionStep.java:34)
        at org.gradle.internal.execution.impl.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:69)
        at org.gradle.internal.execution.impl.steps.TimeoutStep.execute(TimeoutStep.java:49)
        at org.gradle.internal.execution.impl.steps.CatchExceptionStep.execute(CatchExceptionStep.java:34)
        at org.gradle.internal.execution.impl.steps.CreateOutputsStep.execute(CreateOutputsStep.java:49)
        at org.gradle.internal.execution.impl.steps.SnapshotOutputStep.execute(SnapshotOutputStep.java:42)
        at org.gradle.internal.execution.impl.steps.SnapshotOutputStep.execute(SnapshotOutputStep.java:28)
        at org.gradle.internal.execution.impl.steps.CacheStep.executeWithoutCache(CacheStep.java:133)
        at org.gradle.internal.execution.impl.steps.CacheStep.lambda$execute$5(CacheStep.java:83)
        at org.gradle.internal.execution.impl.steps.CacheStep.execute(CacheStep.java:82)
        at org.gradle.internal.execution.impl.steps.CacheStep.execute(CacheStep.java:37)
        at org.gradle.internal.execution.impl.steps.PrepareCachingStep.execute(PrepareCachingStep.java:33)
        at org.gradle.internal.execution.impl.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:38)
        at org.gradle.internal.execution.impl.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:23)
        at org.gradle.internal.execution.impl.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:95)
        at org.gradle.internal.execution.impl.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:88)
        at org.gradle.internal.execution.impl.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:52)
        at org.gradle.internal.execution.impl.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:36)
        at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:34)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:109)
        ... 37 more

**Comment by thomasletsch** [comment]
OK, lets see if we can figure that out.
I'm developing under linux, so I can't say much about MacOS. On my machine I work with an OpenJDK 8, latest version.
The problematic code part where it can't find `io` is apparently the import of `kotlinx.io.core.toByteArray`. Which comes from the lib kotlinx-io. 
It seems that it tries to compile the native MacOS port of the lib, which was probably never really tried out. Stefan (the other contributor) initiated the multi - platform Kotlin Project to get a native Android and JS port as well. Actually I never tried that one out and under Linux no MacOS port is built :-).
Fastest solution is probably to get rid off the MacOS port for now, you can probably just disable it in the gradle build file.

I don't know of any one using the MacOS port of the library...

**Comment by warting** [comment]
Fixed by downgrading kotlin to 1.3.60 and upgraded kotlinx-io to 1.1.16
PR: https://github.com/bisdk/sdk/pull/8

**Comment by warting** [comment]
Still might wanna remove the MacOS port since it will take a while until 0.2 is gonna be released: https://discuss.kotlinlang.org/t/kotlinx-io-release-schedule/16587

**Comment by thomasletsch** [comment]
+1 for removing the MacOS port for now, we have no one really using it currently and the multi-platform is still in an early stage especially for MacOS support.

**Comment by yogitea** [comment]
All. Thank you for taking the time to look at this. Yesterday I also tried to run it in a Ubuntu 18.04 VM and was not successful. I will pull todays changes and see if that works. Otherwise I will post my exact steps to see if this can be fixed as well.

No real need for the MacOS version from my side, since I would like to run it in Docker if possibly anyway.

**Comment by yogitea** [comment]
@thomasletsch @warting I got it to compile on my Ubuntu 18.04
But unfortunately through my very limited knowledge of kotlin and all I can make not good use of it.
Is there any way you could document a way "How to run the RealGatewayTest", so I can try if it is working in my setup?

I know documentation is not easy and time consuming, but it would be appreciated quite a bit! You have done great work reverse engineering the protocol and it would be great to get it used by more people having access to the bisecur gateway. Because the actual vendor App is so bad, I cannot make myself use it.

**Comment by thomasletsch** [comment]
You can execute a certain test by running the following command:
`./gradlew clean jvmTest --tests RealGatewayTest -i`
It executes the test `testStartup`inside `/src/jvmTest/kotlin/org/bisdk/sdk/RealGatewayTest.kt`. It currently (and accidently) assumes that there is a user `openhab`with password `openhab`. Feel free to adjust this value on your local copy and use your real credentials

**Comment by yogitea** [comment]
@thomasletsch Thank you so much. This actually works.

I can see it connecting to my gateway and doing something.
Some timeouts happen, but I am ok with that for now:

Gradle Test Executor 3 finished executing tests.

> Task :jvmTest FAILED

org.bisdk.sdk.RealGatewayTest > testStartup FAILED
    java.lang.IllegalStateException: Retry failed: Received Exception Timeout waiting for PackageReceived (after waiting 5000 ms)
        at org.bisdk.sdk.ClientAPI.sendWithRetry(ClientAPI.kt:277)
        at org.bisdk.sdk.ClientAPI.getTransition(ClientAPI.kt:192)
        at org.bisdk.sdk.RealGatewayTest.testStartup(RealGatewayTest.kt:34)

**Comment by warting** [comment]
For that particular test you need real creadentials to your gateway. This pr clearify it a bit and also let you set the credentials in an env-variable

PR: https://github.com/bisdk/sdk/pull/9/

**Comment by yogitea** [comment]
@warting This is great. I have edited it of course, but having a clean way is always better.

**Comment by yogitea** [comment]
@warting @thomasletsch One more request. Is there a chance you could document the messages and the generation in more detail? I have looked at the code that for example calculates the checksums but could not easily figure it out.

And since I rather not have to learn more Kotlin I started writing the functionality it Python. (will be easier integrated into homekit for me and a lot less code. 
Status: I can replay the messages from the Test and that works fine, but have not implemented the actual creation of them. (Discovery works too.)
To save time I hope you can help me out with understanding the message protocol better. Thank you.

**Comment by thomasletsch** [comment]
A detailed documentation is a different request. You could add a new Issue for that. 
But I hope you understand that documentation is not very high on my prio list ;-), so that could  take  a while...

If the build works for you I propose to close this issue

**Comment by yogitea** [comment]
@thomasletsch Thank you for taking care of this. Closing the issue.
Not tested MacOS, but added Ubuntu option to documentation
